name: Lint and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH  # Make sure uv is in PATH

      - name: Set up virtual environment with uv
        run: |
          uv sync

      - name: Run Ruff
        run: |
          uv run ruff check src

      - name: Run Pyright
        run: |
          uv run pyright src

      - name: Run Pytest
        run: |
          uv run pytest
